name: tag

on:
  push:
    tags:
      - 'v*'

env:
  BIN_DIR: "./bin"
  BIN_NAME: "keygen"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Restore
        run: make restore
      -
        name: Build
        run: make
      -
        name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}
          path: ${{ env.BIN_DIR }}
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Test
        run: make test

  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}
          path: ${{ env.BIN_DIR }}
      -
        name: Create checksums
        working-directory: ${{ env.BIN_DIR }}
        run: |
          find . -type f -print0 | sort -z | xargs -r0 shasum -a 256 -b | sed 's# \*\./# *#' > $RUNNER_TEMP/checksums.txt
          shasum -a 256 -U -c $RUNNER_TEMP/checksums.txt
          mv $RUNNER_TEMP/checksums.txt .
          cat checksums.txt | while read sum file; do echo "$sum $file" > ${file#\*}.sha256; done
      -
        name: List artifacts
        run: |
          find ${{ env.BIN_DIR }} -type f | tr '\n' ','
      -
        name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.BIN_DIR }}
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
